on: [ workflow_dispatch, push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: snok/install-poetry@v1
      - name: Cache poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - run: make install
      - name: Create marker file
        run: echo "setup-complete" > setup-complete.txt
      - name: Upload marker file
        uses: actions/upload-artifact@v4
        with:
          name: setup-marker
          path: setup-complete.txt
          retention-days: 1

  check:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [ lint, types, test ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: snok/install-poetry@v1
      - name: Download marker file
        uses: actions/download-artifact@v4
        with:
          name: setup-marker
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - run: make ${{ matrix.check }}